language: java
jdk:
  - openjdk11

branches: #1
  only:
    - master

# Travis CI 서버의 Home
cache:  #2
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build" #3

# CI 실행 완료 시 메일로 알람
notification:
  email:
    recipients:
      - tlatmdcjf94@gmail.com