version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ubuntu/app/step2/zip/ 
    overwrite: yes

permissions:  #1
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:  #2
  ApplicationStart:
    - location: deploy.sh
      timeout: 60
      runas: ubuntu



